### ISSUE TITLE
Cuda build and x86 Build Not Showing Workers at pool

### ISSUE THREAD

**Issue by Glimmerpride** [Qubic-Solutions/rqiner-builds#23]
Using Cuda build and x86 build together for a CPU and GPU on the same local machine only one worker is visible at the pool. Both the CPU and GPU miners are hashing but the pool only shows the first miner initiated as hashing. Furthermore, only the hash rate from one miner is added to the cumulative total hash rate at the pool. This may just be a backend issue for the Qubic.commando team. (I am assuming MAC address is used for worker identification ) Please let me know what it is (curious).

Thanks

**Comment by trampk** [comment]
I confirm, I have the same error. in this case either appears randomly Label or CPU or GPU miner

cpu miner - rqiner-x86-znver3, Label epyc1
gpu miner - rqiner-x86-cuda, Label 4090


on the pool it shows either 4090 or epyc1, one or the other. But it doesn't show both together

Ubuntu 22.04

**Comment by Arschmole** [comment]
Same here (Ubuntu 22.04.4 LTS). For now, the only way to make it work is using different wallet addresses for the two miner instances running on the same host (i.e, CPU and GPU miner).

**Comment by Dexplorer22** [comment]
[2024-04-06T19:30:45Z INFO  rqiner] Rust > C++ ;)
[2024-04-06T19:30:45Z INFO  rqiner] rqiner v0.3.20
[2024-04-06T19:30:45Z INFO  rqiner] Running Pool Miner
[2024-04-06T19:30:45Z INFO  rqiner] Solution Threshold: 43 | Random Seed: [150, 3, 18, 211, 186, 100, 124, 91, 52, 76, 230, 86, 115, 50, 143, 244, 59, 16, 138, 136, 32, 221, 207, 243, 235, 37, 170, 20, 181, 147, 217, 182]
[2024-04-06T19:31:32Z INFO  rqiner::gpu::pool] Mounted GPU0 NVIDIA GeForce RTX 3070 Ti Laptop GPU 8GB
[2024-04-06T19:31:43Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-06T19:32:07Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-06T19:32:19Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-06T19:32:32Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-06T19:32:44Z INFO  rqiner::gpu::pool] Updating public key
thread '<unnamed>' panicked at rqiner/src/gpu/work_loop.rs:16:67:
called `Result::unwrap()` on an `Err` value: UnknownError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

**Comment by Dexplorer22** [comment]
rqiner-x86-cuda.exe -l 3070 -i BFKFHIPHPQXASCTVRSMDIJDRENVAIXWOCEBQUNIJYFUHFEHBTCQKTKUDPIRH
[2024-04-06T19:36:29Z INFO  rqiner] Rust > C++ ;)
[2024-04-06T19:36:29Z INFO  rqiner] rqiner v0.3.20
[2024-04-06T19:36:29Z INFO  rqiner] Running Pool Miner
[2024-04-06T19:36:30Z INFO  rqiner] Solution Threshold: 43 | Random Seed: [150, 3, 18, 211, 186, 100, 124, 91, 52, 76, 230, 86, 115, 50, 143, 244, 59, 16, 138, 136, 32, 221, 207, 243, 235, 37, 170, 20, 181, 147, 217, 182]
[2024-04-06T19:36:30Z INFO  rqiner::gpu::pool] Mounted GPU0 NVIDIA GeForce RTX 3070 Ti Laptop GPU 8GB
thread '<unnamed>' panicked at rqiner\src\gpu\work_loop.rs:16:67:
called `Result::unwrap()` on an `Err` value: UnknownError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Arschmole** [comment]
Fixed in 0.3.21: https://github.com/Qubic-Solutions/rqiner-builds/releases/tag/v0.3.21-cuda

**Comment by Dexplorer22** [comment]
2024-04-07T04:52:45Z INFO  rqiner] Rust > C++ ;)
[2024-04-07T04:52:45Z INFO  rqiner] rqiner v0.3.21
[2024-04-07T04:52:45Z INFO  rqiner] Running Pool Miner
[2024-04-07T04:52:45Z INFO  rqiner] Solution Threshold: 43 | Random Seed: [150, 3, 18, 211, 186, 100, 124, 91, 52, 76, 230, 86, 115, 50, 143, 244, 59, 16, 138, 136, 32, 221, 207, 243, 235, 37, 170, 20, 181, 147, 217, 182]
[2024-04-07T04:52:45Z INFO  rqiner::gpu::pool] Mounted GPU0 NVIDIA GeForce RTX 3070 Ti Laptop GPU 8GB
[2024-04-07T04:52:46Z ERROR rqiner::gpu::work_loop] Failed to load module: "unknown error" | This issue may be related to drivers, try updating or reinstalling your drivers
[2024-04-07T04:53:21Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-07T04:53:33Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-07T04:54:09Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-07T04:54:21Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-07T04:54:34Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-07T04:54:46Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-07T04:55:46Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-07T04:56:10Z INFO  rqiner::gpu::pool] Updating public key
[2024-04-07T04:56:23Z INFO  rqiner::gpu::pool] Updating public key



qibic-li its worck

**Comment by MaxXue** [comment]
[2024-04-07T10:11:34Z INFO  rqiner] Rust > C++ ;)
[2024-04-07T10:11:34Z INFO  rqiner] rqiner v0.3.21
[2024-04-07T10:11:34Z INFO  rqiner] Running Pool Miner
[2024-04-07T10:11:35Z INFO  rqiner] Solution Threshold: 43 | Random Seed: [150, 3, 18, 211, 186, 100, 124, 91, 52, 76, 230, 86, 115, 50, 143, 244, 59, 16, 138, 136, 32, 221, 207, 243, 235, 37, 170, 20, 181, 147, 217, 182]
[2024-04-07T10:11:35Z INFO  rqiner::gpu::pool] Mounted GPU0 NVIDIA P106-100 6GB
[2024-04-07T10:11:36Z ERROR rqiner::gpu::work_loop] Failed to load module: "unknown error" | This issue may be related to drivers, try updating or reinstalling your drivers
Please，help me 。
